'''
  The Ceasar Cipher is a simple rotational cryptographic algorithm.
  However, it is enhanced with the additions of Vigenère modifications.
'''

class CeasarCipher:
  def __init__(self, shift: str, mask: str) -> None:
      """
      Initialize a CeasarCipher object with a given shift and mask.
  
      Parameters:
      - shift (str): The letter to shift the alphabet by.
      - mask (str): The mask to determine initial state of the matrix.
  
      Returns:
      - None: The function does not return any value.
  
      The __init__ method initializes the following attributes:
      - letters: A list of all uppercase letters of the alphabet.
      - symbol_count: The total number of letters in the alphabet.
      - mask: The mask converted to uppercase.
      - matrix: The generated matrix for encryption and decryption.
      """
      self.letters: list[str] = [
          'A', 'B', 'C', 'D', 'E', 'F',
          'G', 'H', 'I', 'J', 'K', 'L', 'M',
          'N', 'O', 'P', 'Q', 'R', 'S', 'T',
          'U', 'V', 'W', 'X', 'Y', 'Z'
      ]
      self.symbol_count: int = len(self.letters)
      self.mask: str = mask.upper()
      self.matrix: list[list[str]] = self.generateMatrix(shift)
  
  def encrypt(self, text: str) -> str:
    """
    Encrypts the given text using a custom Ceasar Cipher algorithm.

    Parameters:
    - text (str): The text to be encrypted. It can contain both uppercase and lowercase letters, as well as special characters.

    Returns:
    - str: The encrypted text. The returned string will only contain uppercase letters and special characters.

    The encryption process involves shifting each letter in the text based on the corresponding letter in the mask.
    The shift is determined by the position of the letter in the mask and the position of the letter in the alphabet.
    The encrypted text is generated by replacing each letter in the text with the corresponding letter in the matrix,
    where the row index is determined by the letter in the mask and the column index is determined by the letter in the text.
    """
    response: str = ''
    key_idx: int = 0
    for character in text.upper():
      if character.isalpha():
        fidx: int = self.getIndex(self.mask[key_idx])
        sidx: int = self.getIndex(character)
        response += self.matrix[fidx][sidx]
      else:
        response += character
      key_idx = (key_idx + 1) % len(self.mask)
    return response

  def decrypt(self, text: str) -> str:
    """
    Decrypts the given text using the custom Ceasar Cipher algorithm.

    Parameters:
    - text (str): The text to be decrypted. It can contain both uppercase and lowercase letters, as well as special characters.

    Returns:
    - str: The decrypted text. The returned string will only contain uppercase letters and special characters.

    The decryption process involves finding the corresponding letter in the alphabet for each letter in the text based on the
    corresponding letter in the mask and the position of the letter in the matrix.
    The decryption is generated by iterating through each letter in the text, checking if it is an alphabet letter.
    If it is, the corresponding row in the matrix is determined by the letter in the mask, and the column index is found by
    comparing the letter in the matrix row with the letter in the text.
    The decrypted letter is then appended to the response string.
    If the character is not an alphabet letter, it is appended to the response string as is.
    """
    response: str = ''
    key_idx: int = 0
    temp: list[str] = []
    for character in text.upper():
      if character.isalpha():
        temp = self.matrix[self.getIndex(self.mask[key_idx])]
        for j in range(len(temp)):
          if temp[j] == character:
            response += self.letters[j]
      else:
        response += ' '
      key_idx = (key_idx + 1) % len(self.mask)
    return response

  def generateMatrix(self, code: str) -> list[list[str]]:
    """
    Generates a matrix for encryption and decryption based on the given code.

    Parameters:
    - code (str): The letter to shift the alphabet by. It is used to determine the initial state of the matrix.

    Returns:
    - list[list[str]]: The generated matrix. Each row represents a shifted version of the alphabet,
      where the first row is shifted by the index of the code letter in the alphabet.

    The function calculates the index of the code letter in the alphabet and then generates a matrix by shifting
    each row of the alphabet by the corresponding index. The matrix is used for encryption and decryption.
    """
    idx: int = self.getIndex(code)
    matrix: list[list[str]] = []
    for i in range(self.symbol_count):
      row: list[str] = self.letters[idx:] + self.letters[:idx]
      matrix.append(row)
      idx = (idx + 1) % self.symbol_count
    return matrix

  def getIndex(self, letter: str) -> int:
    """
    Get the index of a given letter in the alphabet.

    Parameters:
    - letter (str): The letter to find the index of. The letter should be a single character.

    Returns:
    - int: The index of the given letter in the alphabet. If the letter is not found, returns -1.

    This function takes a letter as input and returns its index in the alphabet.
    The alphabet is represented by the 'letters' attribute of the CeasarCipher class.
    The function converts the letter to uppercase before searching for its index.
    """
    return self.letters.index(letter.upper())

  def printMatrix(self) -> None:
    """
    Prints the generated matrix in a formatted manner.

    The matrix is a 2D list where each row represents a shifted version of the alphabet.
    The first row is shifted by the index of the code letter in the alphabet.
    The matrix is used for encryption and decryption.

    Parameters:
    - None: The function does not take any parameters.

    Returns:
    - None: The function does not return any value.

    The function iterates through each row in the matrix and prints the row elements separated by spaces.
    """
    print('[ ]  ', end='')
    for letter in self.letters:
      print(f"[{letter}] ", end='')
    print('')
    i: int = 0
    for row in self.matrix:
      print(f"[{self.letters[i]}] | ", end='')
      print(' | '.join(row), end='')
      print(' |')
      i += 1

if __name__ == "__main__":
  code: str = 'H'
  mask: str = 'BABBAGE'
  mesg: str = 'HAPPY BIRTHDAY'
  c = CeasarCipher(code, mask)
  # c.printMatrix()
  print(f"Input:     {mesg}")
  encrypted: str = c.encrypt(mesg)
  decrypted: str = c.decrypt(encrypted)
  print(f"Encrypted: {encrypted}\nDecrypted: {decrypted}")
