#!/usr/bin/env Rscript
#
#  The Ceasar Cipher is a simple rotational cryptographic algorithm.
#  However, it is enhanced with the additions of Vigenère modifications.
#

#' @brief Gets the index of a given character in the lexicon.
#'
#' @param code The character to search for in the lexicon.
#' @return The 1-based index of the character in the lexicon, or NA if not found.
get_index <- function(code) {
  match(toupper(code), LETTERS)
}

#' @brief Checks whether a character is a letter in the lexicon (A-Z).
#'
#' @param character The character to check.
#' @return TRUE if the character is between 'A' and 'Z'.
is_letter <- function(character) {
  grepl("^[A-Z]$", character)
}

#' @brief Generates a 2D matrix of characters based on a given code.
#'
#' Each row is the lexicon rotated to start one letter later than the row above it,
#' with the first row starting at the index of the given code. Built without loops:
#' cell [row, col] holds the letter at (code + row + col) mod 26.
#'
#' @param code The character used to determine the starting index for rotating the lexicon.
#' @return A 26x26 character matrix with rows and columns named A-Z.
generate_matrix <- function(code) {
  length <- length(LETTERS)
  idx <- get_index(code)
  offsets <- outer(0:(length - 1), 0:(length - 1), "+")
  matrix(LETTERS[((idx - 1) + offsets) %% length + 1],
         nrow = length, ncol = length,
         dimnames = list(LETTERS, LETTERS))
}

#' @brief Encrypts a message using the Caesar/Vigenère-style matrix and SALT.
#'
#' Each letter is substituted with matrix[row, column], where the row is the index of
#' the current SALT character and the column is the index of the letter. Non-alphabetic
#' characters are preserved as-is. The SALT advances on every character, including spaces.
#'
#' @param cipher_matrix The matrix generated by generate_matrix.
#' @param mask          The SALT string used for masking the message.
#' @param input         The plaintext message to be encrypted.
#' @return The encrypted message.
#'
#' @note Each letter of the input message is converted to uppercase before encryption.
encode <- function(cipher_matrix, mask, input) {
  chars <- strsplit(toupper(input), "")[[1]]
  mask_chars <- strsplit(toupper(mask), "")[[1]]
  output <- character(length(chars))
  key_idx <- 1

  for (i in seq_along(chars)) {
    character <- chars[i]
    if (is_letter(character)) {
      first_idx <- get_index(mask_chars[key_idx])
      second_idx <- get_index(character)
      output[i] <- cipher_matrix[first_idx, second_idx]
    } else {
      output[i] <- character
    }
    key_idx <- (key_idx %% length(mask_chars)) + 1
  }

  paste(output, collapse = "")
}

#' @brief Decrypts a message that was encrypted using the Caesar/Vigenère-style matrix.
#'
#' For each character, it finds the row determined by the current SALT character,
#' searches that row for the encrypted character, and maps the column back to the
#' original alphabet letter. Non-alphabetic characters are preserved as-is. The SALT
#' advances on every character, including spaces.
#'
#' @param cipher_matrix The matrix generated by generate_matrix.
#' @param mask          The SALT string used during encryption.
#' @param input         The encrypted message to be decrypted.
#' @return The decrypted message.
decode <- function(cipher_matrix, mask, input) {
  chars <- strsplit(toupper(input), "")[[1]]
  mask_chars <- strsplit(toupper(mask), "")[[1]]
  output <- character(length(chars))
  key_idx <- 1

  for (i in seq_along(chars)) {
    character <- chars[i]
    if (is_letter(character)) {
      row <- cipher_matrix[get_index(mask_chars[key_idx]), ]
      column <- match(character, row)
      output[i] <- if (is.na(column)) character else LETTERS[column]
    } else {
      output[i] <- character
    }
    key_idx <- (key_idx %% length(mask_chars)) + 1
  }

  paste(output, collapse = "")
}

#' @brief Prints the generated 2D matrix of characters.
#'
#' @param cipher_matrix The matrix generated by generate_matrix.
#' @return void
display_matrix <- function(cipher_matrix) {
  # Headers
  cat("[ ] ", paste0(" [", LETTERS, "]", collapse = ""), "\n", sep = "")
  # Body
  for (i in seq_len(nrow(cipher_matrix))) {
    cat("[", LETTERS[i], "] | ", paste(cipher_matrix[i, ], collapse = " | "), " |\n", sep = "")
  }
}

#' @brief Loads the code, mask, and msg settings from the shared ceasar.ini file.
#'
#' Reads simple key = value lines, skipping blank lines, comments (; or #), and
#' [section] headers. Any setting missing from the file keeps its default value.
#'
#' @param path The path to the ini file.
#' @return A named list holding code, mask, and msg.
load_config <- function(path) {
  config <- list(code = "H", mask = "BABBAGE", msg = "HAPPY BIRTHDAY")
  if (!file.exists(path)) return(config)

  for (line in trimws(readLines(path, warn = FALSE, encoding = "UTF-8"))) {
    if (line == "" || grepl("^[;#[]", line) || !grepl("=", line, fixed = TRUE)) next
    key <- trimws(sub("=.*$", "", line))
    value <- trimws(sub("^[^=]*=", "", line))
    if (key %in% names(config)) config[[key]] <- value
  }

  config
}

# Main Usage (only when run directly with Rscript, not when source()'d)
if (sys.nframe() == 0) {
  # The ini lives beside this script (Rscript passes it as --file=...)
  script_arg <- grep("^--file=", commandArgs(trailingOnly = FALSE), value = TRUE)
  script_dir <- if (length(script_arg)) dirname(sub("^--file=", "", script_arg[1])) else "."
  config <- load_config(file.path(script_dir, "ceasar.ini"))
  code <- config$code
  mask <- config$mask
  mesg <- config$msg
  cipher_matrix <- generate_matrix(code)
  response1 <- encode(cipher_matrix, mask, mesg)
  response2 <- decode(cipher_matrix, mask, response1)
  if (!identical(response2, toupper(mesg))) stop("Round trip failed: ", response2)

  # display_matrix(cipher_matrix)
  cat("Input:     ", mesg, "\n", sep = "")
  cat("Encrypted: ", response1, "\nDecrypted: ", response2, "\n", sep = "")
}
