#!/usr/bin/env perl
=begin comment
  The Ceasar Cipher is a simple rotational cryptographic algorithm.
  However, it is enhanced with the additions of Vigenère modifications.
=cut
use strict;
use warnings;
use File::Basename qw(dirname);
use File::Spec;

use constant LETTERS => "ABCDEFGHIJKLMNOPQRSTUVWXYZ";

#!
# @brief Decrypts a message that was encrypted using the Caesar/Vigenère-style matrix.
#
# For each character, it finds the row determined by the current SALT character,
# searches that row for the encrypted character, and maps the column back to the
# original alphabet letter. Non-alphabetic characters are preserved as-is. The SALT
# advances on every character, including spaces.
#
# @param matrix_ref Reference to the 2D matrix generated by generate_matrix.
# @param mask       The SALT string used during encryption.
# @param input      The encrypted message to be decrypted.
# @return The decrypted message.
#
sub decode {
  my ($matrix_ref, $mask, $input) = @_;
  $mask = uc $mask;
  my $output = '';
  my $key_idx = 0;

  for my $character (split //, uc $input) {
    if (is_letter($character)) {
      my $row = $matrix_ref->[get_index(substr($mask, $key_idx, 1))];
      my ($column) = grep { $row->[$_] eq $character } 0 .. $#$row;
      $output .= defined($column) ? substr(LETTERS, $column, 1) : $character;
    } else {
      $output .= $character;
    }
    $key_idx = ($key_idx + 1) % length($mask);
  }

  return $output;
}

#!
# @brief Encrypts a message using the Caesar/Vigenère-style matrix and SALT.
#
# Each letter is substituted with matrix[row][column], where the row is the index of
# the current SALT character and the column is the index of the letter. Non-alphabetic
# characters are preserved as-is. The SALT advances on every character, including spaces.
#
# @param matrix_ref Reference to the 2D matrix generated by generate_matrix.
# @param mask       The SALT string used for masking the message.
# @param input      The plaintext message to be encrypted.
# @return The encrypted message.
#
# @note Each letter of the input message is converted to uppercase before encryption.
#
sub encode {
  my ($matrix_ref, $mask, $input) = @_;
  $mask = uc $mask;
  my $output = '';
  my $key_idx = 0;

  for my $character (split //, uc $input) {
    if (is_letter($character)) {
      my $first_idx = get_index(substr($mask, $key_idx, 1));
      my $second_idx = get_index($character);
      $output .= $matrix_ref->[$first_idx][$second_idx];
    } else {
      $output .= $character;
    }
    $key_idx = ($key_idx + 1) % length($mask);
  }

  return $output;
}

#!
# @brief Generates a 2D matrix of characters based on a given code.
#
# Each row is the lexicon rotated to start one letter later than the row above it,
# with the first row starting at the index of the given code.
#
# @param code The character used to determine the starting index for rotating the lexicon.
# @return A reference to the 2D matrix (array of arrays of characters).
#
sub generate_matrix {
  my ($code) = @_;
  my $letters = LETTERS;
  my $index = get_index($code);
  my @matrix;

  for my $i (0 .. length($letters) - 1) {
    my $rotated = substr($letters, $index) . substr($letters, 0, $index);
    push @matrix, [ split //, $rotated ];
    $index = ($index + 1) % length($letters);
  }

  return \@matrix;  # return reference to 2D array
}

#!
# @brief Gets the index of a given character in the lexicon.
#
# @param code The character to search for in the lexicon.
# @return The index of the character in the lexicon, or -1 if not found.
#
sub get_index {
  my ($code) = @_;
  return index(LETTERS, uc $code);
}

#!
# @brief Checks whether a character is a letter in the lexicon (A-Z).
#
# @param character The character to check.
# @return True if the character is between 'A' and 'Z'.
#
sub is_letter {
  my ($character) = @_;
  return $character =~ /^[A-Z]$/;
}

#!
# @brief Prints the generated 2D matrix of characters.
#
# @param matrix_ref Reference to the 2D matrix generated by generate_matrix.
# @return void
#
sub display_matrix {
  my ($matrix_ref) = @_;
  my @matrix = @$matrix_ref;  # dereference the 2D array reference
  my $letters = LETTERS;

  # Print header row
  print "[ ] ";
  for my $ch (split //, $letters) {
    printf " [%s]", $ch;
  }
  print "\n";

  # Print each matrix row
  for my $i (0 .. $#matrix) {
    printf "[%s] ", substr($letters, $i, 1);
    for my $j (0 .. $#{$matrix[$i]}) {
      printf "| %s ", $matrix[$i][$j];
    }
    print "|\n";
  }
}

#!
# @brief Loads the code, mask, and msg settings from the shared ceasar.ini file.
#
# Reads simple key = value lines, skipping blank lines, comments (; or #), and
# [section] headers. Any setting missing from the file keeps its default value.
#
# @param path The path to the ini file.
# @return A hash reference holding code, mask, and msg.
#
sub load_config {
  my ($path) = @_;
  my %config = (code => 'H', mask => 'BABBAGE', msg => 'HAPPY BIRTHDAY');

  open(my $fh, '<:encoding(UTF-8)', $path) or return \%config;
  while (my $line = <$fh>) {
    $line =~ s/^\s+|\s+$//g;
    next if $line eq '' || $line =~ /^[;#\[]/;
    my ($key, $value) = split /=/, $line, 2;
    next unless defined $value;
    $key =~ s/^\s+|\s+$//g;
    $value =~ s/^\s+|\s+$//g;
    $config{$key} = $value if exists $config{$key};
  }
  close($fh);

  return \%config;
}

unless (caller) {
  my $config = load_config(File::Spec->catfile(dirname(__FILE__), 'ceasar.ini'));
  my $code = $config->{code};
  my $mask = $config->{mask};
  my $mesg = $config->{msg};
  my $matrix = generate_matrix($code);
  my $response1 = encode($matrix, $mask, $mesg);
  my $response2 = decode($matrix, $mask, $response1);
  die "Round trip failed: $response2\n" unless $response2 eq uc $mesg;

  # display_matrix($matrix);
  print "Input:     $mesg\n";
  print "Encrypted: $response1\nDecrypted: $response2\n";
}

1;
