#!/usr/bin/env lua

--[[
  The Ceasar Cipher is a simple rotational cryptographic algorithm.
  However, it is enhanced with the additions of Vigenère modifications.
]]

--[[!
  @brief Gets the lexicon (alphabet) used by the cipher.

  @return The uppercase alphabet as a string.
]]
local function get_letters()
  return "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
end

--[[!
  @brief Gets the index of a given character in the lexicon.

  @param c The character to search for in the lexicon.
  @return The 1-based index of the character in the lexicon, or nil if not found.
]]
local function get_index(c)
  local letters = get_letters()
  return (string.find(letters, c:upper(), 1, true))
end

--[[!
  @brief Checks whether a character is a letter in the lexicon (A-Z).

  @param c The character to check.
  @return True if the character is between 'A' and 'Z'.
]]
local function is_letter(c)
  return c:match("^[A-Z]$") ~= nil
end

--[[!
  @brief Generates a 2D matrix of characters based on a given code.

  Each row is the lexicon rotated to start one letter later than the row above it,
  with the first row starting at the index of the given code.

  @param code The character used to determine the starting index for rotating the lexicon.
  @return A table of row strings representing the generated matrix.
]]
local function generate_matrix(code)
  local matrix = {}
  local letters = get_letters()
  local idx = get_index(code)
  for i = 1, #letters do
    table.insert(matrix, string.sub(letters, idx) .. string.sub(letters, 1, idx - 1))
    idx = (idx % #letters) + 1
  end
  return matrix
end

--[[!
  @brief Encrypts a message using the Caesar/Vigenère-style matrix and SALT.

  Each letter is substituted with matrix[row][column], where the row is the index of
  the current SALT character and the column is the index of the letter. Non-alphabetic
  characters are preserved as-is. The SALT advances on every character, including spaces.

  @param matrix The matrix generated by generate_matrix.
  @param salt   The SALT string used for masking the message.
  @param input  The plaintext message to be encrypted.
  @return The encrypted message.

  @note Each letter of the input message is converted to uppercase before encryption.
]]
local function encode(matrix, salt, input)
  local output = {}
  local salt_chars = {salt:upper():byte(1, #salt)}
  local salt_len = #salt_chars
  local salt_index = 1

  for c in input:upper():gmatch(".") do
    if is_letter(c) then
      local row = matrix[get_index(string.char(salt_chars[salt_index]))]
      local col = get_index(c)
      table.insert(output, string.sub(row, col, col))
    else
      table.insert(output, c)
    end
    salt_index = (salt_index % salt_len) + 1
  end
  return table.concat(output)
end

--[[!
  @brief Decrypts a message that was encrypted using the Caesar/Vigenère-style matrix.

  For each character, it finds the row determined by the current SALT character,
  searches that row for the encrypted character, and maps the column back to the
  original alphabet letter. Non-alphabetic characters are preserved as-is. The SALT
  advances on every character, including spaces.

  @param matrix The matrix generated by generate_matrix.
  @param salt   The SALT string used during encryption.
  @param input  The encrypted message to be decrypted.
  @return The decrypted message.
]]
local function decode(matrix, salt, input)
  local output = {}
  local salt_chars = {salt:upper():byte(1, #salt)}
  local salt_len = #salt_chars
  local salt_index = 1
  local letters = get_letters()

  for c in input:upper():gmatch(".") do
    if is_letter(c) then
      local row = matrix[get_index(string.char(salt_chars[salt_index]))]
      local col = string.find(row, c, 1, true)
      table.insert(output, col and string.sub(letters, col, col) or c)
    else
      table.insert(output, c)
    end
    salt_index = (salt_index % salt_len) + 1
  end
  return table.concat(output)
end

--[[!
  @brief Prints the generated 2D matrix of characters.

  @param matrix The matrix generated by generate_matrix.
  @return void
]]
local function display_matrix(matrix)
  local letters = get_letters()

  -- header row
  io.write("[ ]  ")
  for i = 1, #letters do
    io.write(string.format("[%s] ", letters:sub(i, i)))
  end
  io.write("\n")

  -- each row
  for i = 1, #matrix do
    io.write(string.format("[%s] ", letters:sub(i, i)))
    for j = 1, #matrix[i] do
      io.write(string.format("| %s ", matrix[i]:sub(j, j)))
    end
    io.write("|\n")
  end
end

--[[!
  @brief Loads the code, mask, and msg settings from the shared ceasar.ini file.

  Reads simple key = value lines, skipping blank lines, comments (; or #), and
  [section] headers. Any setting missing from the file keeps its default value.

  @param path The path to the ini file.
  @return A table holding code, mask, and msg.
]]
local function load_config(path)
  local config = { code = "H", mask = "BABBAGE", msg = "HAPPY BIRTHDAY" }
  local file = io.open(path, "r")
  if not file then return config end

  for line in file:lines() do
    line = line:match("^%s*(.-)%s*$")
    if line ~= "" and not line:match("^[;#%[]") then
      local key, value = line:match("^(.-)%s*=%s*(.-)$")
      if key and config[key] then config[key] = value end
    end
  end
  file:close()

  return config
end

-- Main Usage (only when run directly; `...` holds the module name when required)
if not ... then
  -- The ini lives beside this script
  local script_dir = debug.getinfo(1, "S").source:match("^@(.*[/\\])") or "./"
  local config = load_config(script_dir .. "ceasar.ini")
  local code     = config.code
  local salt     = config.mask
  local msg      = config.msg

  -- Build the cipher matrix
  local matrix = generate_matrix(code)

  -- Encrypt
  local encrypted = encode(matrix, salt, msg)

  -- Decrypt
  local decrypted = decode(matrix, salt, encrypted)
  assert(decrypted == msg:upper(), "Round trip failed: " .. decrypted)

  -- Show matrix
  -- display_matrix(matrix)

  -- Print results
  print("Input:     " .. msg)
  print("Encrypted: " .. encrypted)
  print("Decrypted: " .. decrypted)
end

return {
  generate_matrix = generate_matrix,
  encode = encode,
  decode = decode,
  display_matrix = display_matrix,
  load_config = load_config,
}
